// Academia do Bairro objects for the language diary (see ../diaryItems.mjs for the palette).
export const ACADEMIA = {
  cronometro: [
    '..yy..',
    '.dddd.',
    'dwwkwd',
    'dwwkkd',
    'dwwwwd',
    '.dddd.',
  ],
  apito: [
    '.dddd...',
    'dyyyydd.',
    'dyyyyyyd',
    'dyyyyyyd',
    '.dddddd.',
  ],
  prancheta: [
    '..dd..',
    '.dddd.',
    'dwwwwd',
    'dwgggd',
    'dwwwwd',
    'dwgggd',
    'dwwwwd',
    'dddddd',
  ],
  medalha: [
    'bb..rr',
    '.bbrr.',
    '..yy..',
    '.yYYy.',
    'yYooYy',
    'yYooYy',
    '.yYYy.',
    '..yy..',
  ],
  trofeu: [
    'y.yyyy.y',
    'yyyyyyyy',
    '.yYyyyy.',
    '..yyyy..',
    '...yy...',
    '...yy...',
    '..dddd..',
    '.dddddd.',
  ],
  corda: [
    '.nnnnnn.',
    'nTTTTTTn',
    'nT....Tn',
    'nTTTTTTn',
    '.nnnnnn.',
  ],
  armario: [
    'dddddddd',
    'dbbbbbbd',
    'dbddddbd',
    'dbbbbbbd',
    'dbbbbbbd',
    'dbbbbybd',
    'dbbbbbbd',
    'dbbbbbbd',
    'dddddddd',
  ],
  recepcao: [
    'tttttttttttt',
    'TTTTTTTTTTTT',
    'nnnnnnnnnnnn',
    'nTTTTTTTTTTn',
    'nTTTTTTTTTTn',
    'nnnnnnnnnnnn',
  ],
  computador: [
    'dddddddd',
    'dbbbbbbd',
    'dbwwwwbd',
    'dbbbbbbd',
    'dddddddd',
    '...dd...',
    '.dddddd.',
  ],
  podio: [
    '....yyyy....',
    '....yYYy....',
    '....yyyy....',
    'ggggyyyybbbb',
    'gwwgyyyybwwb',
    'ggggyyyybbbb',
  ],
  meia: [
    '.wwww..',
    '.wbbw..',
    '.wwww..',
    '.wwww..',
    '.wwwwww',
    '.wwwwww',
    '..wwwww',
  ],
  squeeze: [
    '..rr..',
    '..dd..',
    '.cccc.',
    'cwuucc',
    'cwuucc',
    'cwuucc',
    'cwuucc',
    '.cccc.',
  ],
  isotonico: [
    '..dd..',
    '.dddd.',
    '.oooo.',
    'oYooOo',
    'oooooo',
    'oooooo',
    '.oooo.',
  ],
};
