// The airport hall behind the arrival card: the fourteen camera words of the Chegada area (see ../diaryItems.mjs for the palette).
// The hall is a postcard in the client (ui/arrivalHall.ts), not a room: these grids are drawn there, not in the world atlas.

export const CHEGADA = {
  mala: [
    '...dd...',
    '..d..d..',
    'bbbbbbbb',
    'bBBBBBBb',
    'bBbbbbBb',
    'bBBBBBBb',
    'bbbbbbbb',
    '.d....d.',
  ],
  passaporte: [
    'BBBBBBB',
    'ByyyyyB',
    'ByyYyyB',
    'ByyyyyB',
    'ByyyyyB',
    'BBBBBBB',
  ],
  esteira: [
    'dddddddddddddddd',
    'kgkgkgkgkgkgkgkg',
    'dddddddddddddddd',
    'g..g..g..g..g..g',
  ],
  mochila: [
    '..dddd..',
    '.d....d.',
    'eeeeeeee',
    'eEEEEEEe',
    'eEddddEe',
    'eEEEEEEe',
    'eEEyyEEe',
    'eeeeeeee',
  ],
  pista: [
    'dddddddddddd',
    'dddddddddddd',
    'dwwdwwdwwdww',
    'dddddddddddd',
    'dddddddddddd',
  ],
  torre: [
    '..bbbbbb..',
    '.bccccccb.',
    '.bcwcwccb.',
    '.bbbbbbbb.',
    '...gggg...',
    '...gwwg...',
    '...gwwg...',
    '...gwwg...',
    '...gwwg...',
    '..gggggg..',
  ],
  ponte: [
    'gggggggggggg',
    'gcccccccccgg',
    'gcwcwcwcwcgg',
    'gcccccccccgg',
    'gggggggggggg',
    '.d........d.',
  ],
  cinto: [
    'dddddddddddd',
    'dggggggggggd',
    'dddddddddyyd',
    '..........yd',
  ],
  asa: [
    '...........ww',
    '.........wwww',
    '.......wwwwww',
    '.....wwwwwwgg',
    '...wwwwwwwgg.',
    'wwwwwwwwggg..',
    'wwwwgggggg...',
  ],
  fone: [
    '..dddddd..',
    '.d......d.',
    'd........d',
    'dd......dd',
    'rr......rr',
    'rr......rr',
  ],
  bilhete: [
    'wwwwwwwwww',
    'wbbbbbwiiw',
    'wwwwwwwiiw',
    'wgggggwiiw',
    'wwwwwwwwww',
  ],
  visto: [
    '.rrrrrrr.',
    'rRRRRRRRr',
    'rRwrrrwRr',
    'rRrrwrrRr',
    'rRwrrrwRr',
    'rRRRRRRRr',
    '.rrrrrrr.',
  ],
  etiqueta: [
    '.kk.....',
    'k..kkkkk',
    'k..kwwwk',
    '.kkkwbwk',
    '....kwwk',
    '.....kkk',
  ],
  turbina: [
    '..dddddd..',
    '.dgggggggd',
    'dgdddddddg',
    'dgdkkkkdgd',
    'dgdkwwkdgd',
    'dgdkkkkdgd',
    'dgdddddddg',
    '.dgggggggd',
    '..dddddd..',
  ],
};
