// Kitnet objects for the language diary (see ../diaryItems.mjs for the palette).
export const KITNET = {
  travesseiro: [
    'wwwwwwww',
    'wiiiiiiw',
    'wiwwwwiw',
    'wiiiiiiw',
    'wwwwwwww',
  ],
  lencol: [
    'cccccccccc',
    'cuuuuuuuuc',
    'cuccccccuc',
    'cuuuuuuuuc',
    'cccccccccc',
  ],
  cobertor: [
    'rrrrrrrrrr',
    'rRrRrRrRrr',
    'rrrrrrrrrr',
    'rRrRrRrRrr',
    'rrrrrrrrrr',
  ],
  edredom: [
    '.bbbbbbbb.',
    'bBBbbBBbbb',
    'bBBbbBBbbb',
    'bbbBBbbBBb',
    'bbbBBbbBBb',
    '.bbbbbbbb.',
  ],
  colchao: [
    'wwwwwwwwwwww',
    'wiiiiiiiiiiw',
    'wiwwwwwwwwiw',
    'wiiiiiiiiiiw',
    'wwwwwwwwwwww',
  ],
  fronha: [
    'wwwwwwww',
    'wbbbbbbw',
    'wwwwwwww',
    'wiiiiiiw',
    'wwwwwwww',
  ],
  abajur: [
    '..yyyy..',
    '.yYYYYy.',
    'yYYYYYYy',
    'yyyyyyyy',
    '...dd...',
    '...dd...',
    '..dddd..',
  ],
  guarda_roupa: [
    'nnnnnnnnnn',
    'nTTTTnTTTn',
    'nTTTTnTTTn',
    'nTTTTnTTTn',
    'nTTyTnyTTn',
    'nTTTTnTTTn',
    'nTTTTnTTTn',
    'nTTTTnTTTn',
    'nnnnnnnnnn',
    '.N......N.',
  ],
  cabide: [
    '..gg..',
    '..g...',
    '.ggg..',
    'g...g.',
    'gggggg',
  ],
  comoda: [
    'tttttttttt',
    'tTTTTTTTTt',
    'tTyTTTTyTt',
    'nnnnnnnnnn',
    'tTTTTTTTTt',
    'tTyTTTTyTt',
    'nnnnnnnnnn',
    '.N......N.',
  ],
  cortina: [
    'dddddddddd',
    'rRrr..rrRr',
    'rRrr..rrRr',
    'rRrr..rrRr',
    'rRrr..rrRr',
    '.Rr....rR.',
  ],
  chinelo: [
    '..bb..',
    '.bbbb.',
    '.bwwb.',
    '.bbbb.',
    '.bbbb.',
    '.bbbb.',
    '.bbbb.',
    '..bb..',
  ],
  oculos: [
    'dddd.dddd',
    'dccdddccd',
    'dccd.dccd',
    '.dd...dd.',
  ],
  espelho: [
    '.TTTTTT.',
    'TcccwwcT',
    'TccwwccT',
    'TcwwcccT',
    'TccccccT',
    'TccccccT',
    '.TTTTTT.',
  ],
  fogao: [
    'wwwwwwwwww',
    'wdkdwwdkdw',
    'wkkkwwkkkw',
    'wdkdwwdkdw',
    'wwwwwwwwww',
    'wggggggggw',
    'wgwwwwwwgw',
    'wgwwwwwwgw',
    'wwwwwwwwww',
  ],
  pia: [
    '..g..g....',
    'dddddddddd',
    'dccccccccd',
    'dccccccccd',
    'dddddddddd',
  ],
  torneira: [
    '.gggg..',
    'gwwwwg.',
    'ggggggg',
    '....gg.',
    '....gg.',
    '....gg.',
  ],
  sabao: [
    '.bbbbbbb.',
    'bBbbbbbbb',
    'bbbbbbbbb',
    '.bbbbbbb.',
  ],
  prato: [
    '.wwwwww.',
    'wwiiiiww',
    'wiwwwwiw',
    'wwiiiiww',
    '.wwwwww.',
  ],
  garfo: [
    'g.g.g',
    'g.g.g',
    'ggggg',
    '.ggg.',
    '..g..',
    '..g..',
    '..g..',
  ],
  frigideira: [
    '.dddddd...',
    'dggggggdnn',
    'dgkkkkgdnn',
    'dgkkkkgd..',
    'dggggggd..',
    '.dddddd...',
  ],
  tampa: [
    '..dd..',
    '.gwwg.',
    'ggwggg',
    'gggggg',
    'dddddd',
  ],
  micro_ondas: [
    'dddddddddd',
    'dggggggkkd',
    'dgbbbbgkyd',
    'dgbbbbgkkd',
    'dgbbbbgkkd',
    'dggggggggd',
    'dddddddddd',
  ],
  chaleira: [
    '..gg....',
    '.dddd...',
    'dggggdd.',
    'dgwggg.d',
    'dggggg.d',
    'dggggdd.',
    '.dddd...',
  ],
  chuveiro: [
    '.dd.....',
    '..d.....',
    '..dddd..',
    '.dggggd.',
    'dggggggd',
    '.c.c.c..',
    '..c.c.c.',
    '.c.c.c..',
  ],
  toalha: [
    'bbbbbbbb',
    'bBBBBBBb',
    'bbbbbbbb',
    'wwwwwwww',
    'bbbbbbbb',
    'bBBBBBBb',
    'bbbbbbbb',
  ],
  xampu: [
    '..bb..',
    '.bbbb.',
    '.bwwb.',
    '.bwwb.',
    '.bbbb.',
    '.bbbb.',
  ],
  box: [
    'cccccccccc',
    'cwcccccccc',
    'cwcccccccc',
    'cwcccccccc',
    'cwcccccccc',
    'cwcccccccc',
    'cwcccccccc',
    'dddddddddd',
  ],
  escova: [
    '.rrrrrr...',
    'rkkkkkkrnn',
    'rkkkkkkrnn',
    '.rrrrrr...',
  ],
  creme: [
    'rr......',
    'rwwwwwww',
    'rwbbbbww',
    'rwwwwwww',
    'rr......',
  ],
  pente: [
    'wwwwwwwwww',
    'wwwwwwwwww',
    'w.w.w.w.w.',
    'w.w.w.w.w.',
  ],
  varal: [
    'k........k',
    'kkkkkkkkkk',
    '.r..b..y..',
    '.rr.bb.yy.',
    '.rr.bb.yy.',
  ],
  pregador: [
    '.nn.',
    '.nn.',
    '.nn.',
    'nnnn',
    'n..n',
  ],
  tomada: [
    'iiiiiii',
    'iwwwwwi',
    'iwkwkwi',
    'iwkwkwi',
    'iwwwwwi',
    'iiiiiii',
  ],
  interruptor: [
    'iiiiii',
    'iwwwwi',
    'iwddwi',
    'iwddwi',
    'iwwwwi',
    'iiiiii',
  ],
  carregador: [
    '..ddd..',
    '.dwwwd.',
    '.dwwwd.',
    '.dwwwd.',
    '..ddd..',
    '...k...',
    '...k...',
    '...k...',
  ],
  retrato: [
    'nnnnnnnn',
    'nuuuuuun',
    'nuuyyuun',
    'nuussuun',
    'nuussuun',
    'nnnnnnnn',
  ],
  perfume: [
    '..yy..',
    '..gg..',
    '.pppp.',
    'pwPPpp',
    'pPPPPp',
    'pppppp',
  ],
  despertador: [
    'g..gg..g',
    '.dddddd.',
    'dwwkwwwd',
    'dwwkkwwd',
    'dwwwwwwd',
    '.dddddd.',
    '.d....d.',
  ],
  extensao: [
    'dddddddddd',
    'dkkdkkdkkd',
    'dkkdkkdkkd',
    'dddddddddd',
    '.k........',
    '.k........',
  ],
  racao: [
    '..oooo..',
    '.oYYYYo.',
    'oYYkYkYo',
    'oYYYYYYo',
    'oYYkkkYo',
    'oYYYYYYo',
    'oooooooo',
  ],
  pote: [
    '.dddddd.',
    'cccccccc',
    'cwwwwwwc',
    'cwttttwc',
    'cwttttwc',
    'cwwwwwwc',
    'cccccccc',
  ],
  chave: [
    '.yyy....',
    'y.Yy....',
    'y..yyyyy',
    '.yyy.y.y',
  ],
};
