// Padaria do Seu Carlos objects for the language diary (see ../diaryItems.mjs for the palette).
export const PADARIA = {
  bandeja: [
    'dddddddddd',
    'dggggggggd',
    'dggggggggd',
    'dddddddddd',
  ],
  forno: [
    'dddddddddd',
    'dgyggggygd',
    'dddddddddd',
    'dgkkkkkkgd',
    'dgkooookgd',
    'dgkoyyokgd',
    'dgkooookgd',
    'dgkkkkkkgd',
    'dggggggggd',
    'dddddddddd',
    '.dd....dd.',
  ],
  chapa: [
    'dddddddddd',
    'dggggggggd',
    'dgdgdgdgdd',
    'dggggggggd',
    'dddddddddd',
  ],
  cafeteira: [
    '.dddddd.',
    '.dggggd.',
    '.dgkkgd.',
    '.dgkkgd.',
    '.dddddd.',
    '.dcccwd.',
    '.dcnnnd.',
    '.dddddd.',
  ],
  pires: [
    '.wwwwww.',
    'wwiiiiww',
    '.wwwwww.',
  ],
  leite: [
    '..ww..',
    '.wwww.',
    'wwwwww',
    'wbbbbw',
    'wbwwbw',
    'wbbbbw',
    'wwwwww',
  ],
  faca: [
    'nnnnggggg.',
    'nnnngwwwwg',
    '....ggggg.',
  ],
  tabua: [
    '.ttttttttt.',
    'tTTTTTTTTTt',
    'tTTTTTTTTTt',
    'tTTTTTTTTTt',
    'tTTTTTTTTTt',
    '.ttttttttt.',
  ],
  avental: [
    '.ww..ww.',
    '.wwwwww.',
    'wwwwwwww',
    'wwwwwwww',
    'wwiiiiww',
    'wwwwwwww',
    'wwwwwwww',
  ],
  touca: [
    '..wwww..',
    '.wiwiww.',
    'wiwiwiww',
    'wwiwiwiw',
    'wwwwwwww',
  ],
  prateleira: [
    '..tt..tt..',
    '.tTTtTTTt.',
    'nnnnnnnnnn',
    'N........N',
  ],
  pao: [
    '..tTTTt..',
    '.tTTtTTt.',
    'tTtTTtTTt',
    'tTTTTTTTt',
    '.tttttttt',
    '..nnnnn..',
  ],
  torrada: [
    '.tttttt.',
    'tTTTTTTt',
    'tTnTTnTt',
    'tTTTTTTt',
    'tTTTTTTt',
    '.tttttt.',
  ],
  manteiga: [
    '..yyyyy..',
    '.yYYYYYy.',
    'yyyyyyyyy',
    'wwwwwwwww',
    '.wwwwwww.',
  ],
  requeijao: [
    '.wwwwwww.',
    'wiiiiiiiw',
    'wbbbbbbbw',
    'wbwwwwwbw',
    'wbbbbbbbw',
    '.wwwwwww.',
  ],
  presunto: [
    '.pppppp.',
    'ppPPppPp',
    'pPppppPp',
    'ppppPppp',
    '.pppppp.',
  ],
  ovo: [
    '..TT..',
    '.TTTT.',
    'TYTTTt',
    'TTTTTt',
    'TTTTtt',
    '.tttt.',
  ],
  geladeira: [
    '.iiiiiiii.',
    'iwwwwwwwwi',
    'iwwwwwwwwi',
    'iwwwwgwwwi',
    'iiiiiiiiii',
    'iwwwwwwwwi',
    'iwwwwgwwwi',
    'iwwwwgwwwi',
    'iwwwwwwwwi',
    'iwwwwwwwwi',
    'iiiiiiiiii',
    '.d......d.',
  ],
  freezer: [
    'bbbbbbbbbb',
    'bwwwwwwwwb',
    'bwwwwwwwwb',
    'bbbbbbbbbb',
    'iwwwwwwwwi',
    'iwwwwwwgwi',
    'iiiiiiiiii',
    '.d......d.',
  ],
  xicara: [
    '.nnnn...',
    'wwwwww..',
    'wiiiiww.',
    'wiiiiw.w',
    '.wiiw.ww',
    '..ww..w.',
    'wwwwwwww',
  ],
  jarra: [
    '.cccccc.',
    'cooooooc',
    'cooooooc',
    'cooooooc',
    'cooooooc',
    '.cccccc.',
  ],
  liquidificador: [
    '..cccc..',
    '.cwwwwc.',
    '.cwwwwc.',
    '.cwwwwc.',
    '..cccc..',
    '..dddd..',
    '.dggggd.',
    '.dddddd.',
  ],
  comanda: [
    'wwwwwww',
    'wrrrrrw',
    'wgggggw',
    'wiiiiiw',
    'wgggggw',
    'wwwwwww',
  ],
  ficha: [
    'yyyyyyyy',
    'ykkkkkky',
    'yyyyykyy',
    'yyyykyyy',
    'yyykyyyy',
    'yyykyyyy',
    'yyyyyyyy',
  ],
  sineta: [
    '..dd..',
    '.gggg.',
    'gwwwwg',
    'gggggg',
    'dddddd',
  ],
  gaveta: [
    'dddddddddd',
    'dggggggggd',
    'dgyyyyyygd',
    'dggggggggd',
    'dddddddddd',
    '.dd....dd.',
  ],
  maquininha: [
    '.dddddd.',
    'dbbbbbbd',
    'dbwwwwbd',
    'dbbbbbbd',
    'dgygygyd',
    'dggggggd',
    'dgygygyd',
    'dddddddd',
  ],
  sabonete: [
    '.pppppp.',
    'pPppppPp',
    'pppppppp',
    '.pppppp.',
  ],
  detergente: [
    '..yy..',
    '..yy..',
    '.eeee.',
    'eeeeee',
    'ewwwwe',
    'eeeeee',
    'eeeeee',
  ],
  esponja: [
    'yyyyyyy',
    'yyyoyyy',
    'yoyyyoy',
    'yyyyyyy',
    'eeeeeee',
  ],
  embalagem: [
    'wwwwwww',
    'wTTTTTw',
    'wTwwwTw',
    'wTTTTTw',
    'wwwwwww',
  ],
  acucar: [
    '.wwwwww.',
    'wiiiiiiw',
    'wwwwwwww',
    '.wwwwww.',
    '..wwww..',
  ],
  colher: [
    'ggg.....',
    'gwwggggg',
    'ggg.....',
  ],
};
