// Praça objects for the language diary. One entry per camera word: rows of equal width, `.` is empty (see ../diaryItems.mjs for the palette).
// The generator adds the 1 px navy outline around every shape, so the art here is drawn without it.
export const PRACA = {
  paralelepipedo: [
    '..gggg..',
    '.gllllg.',
    'glllllgg',
    'gllllggd',
    '.gggggd.',
  ],
  folha: [
    '....ee..',
    '..eefEe.',
    '.efffEE.',
    'effEEEe.',
    '.eEEEe..',
    'n.eEe...',
    '.n......',
  ],
  relogio: [
    '.wwwwww.',
    'wwkkkkww',
    'wkwwkwwk',
    'wkwkkwwk',
    'wkwwwkwk',
    'wwkkkkww',
    '.wwwwww.',
    '...dd...',
    '...dd...',
    '...dd...',
    '...dd...',
    '..dddd..',
  ],
  estatua: [
    '...gg...',
    '..gllg..',
    '..glgg..',
    '...gg...',
    '..gllg..',
    '.gllllg.',
    '.gl..lg.',
    '..gllg..',
    '.gggggg.',
    'dddddddd',
  ],
  guarda_sol: [
    '..rrrr..',
    '.rwrwrr.',
    'rwrwrwrr',
    'rrrrrrrr',
    '...nn...',
    '...nn...',
    '...nn...',
    '..nnnn..',
  ],
  cesta: [
    '.n....n.',
    '.nnnnnn.',
    'ntntntnt',
    'tntntntn',
    'ntntntnt',
    '.nnnnnn.',
  ],
  garrafa: [
    '..cc..',
    '..cc..',
    '.cccc.',
    '.cuuc.',
    '.cuuc.',
    '.cuuc.',
    '.cuuc.',
    '.cccc.',
  ],
  copo: [
    'wwwwww',
    'wiiiiw',
    '.wiiw.',
    '.wiiw.',
    '..ww..',
  ],
  lata: [
    '.gggg.',
    'gwwwwg',
    'rrrrrr',
    'rwwwwr',
    'rrrrrr',
    'gwwwwg',
    '.gggg.',
  ],
  bolsa: [
    '..nn..',
    '.n..n.',
    'nnnnnn',
    'ttTTtt',
    'ttTTtt',
    'tttttt',
    'nnnnnn',
  ],
  moeda: [
    '.yyyy.',
    'yYyyyy',
    'yyyoyy',
    'yyyyoy',
    '.yyoo.',
  ],
  cedula: [
    'ggggggggg',
    'gfffYfffg',
    'gfeeYeefg',
    'gfeYYYefg',
    'gfeeYeefg',
    'gfffYfffg',
    'ggggggggg',
  ],
  celular: [
    '.dddd.',
    'dbbbbd',
    'dbwwbd',
    'dbbbbd',
    'dbbbbd',
    'dbbbbd',
    'dbbbbd',
    '.dddd.',
  ],
  folheto: [
    'wwwwwww',
    'wrrrrrw',
    'wiiiiiw',
    'wiggggw',
    'wiiiiiw',
    'wiggggw',
    'wwwwwww',
  ],
  cartaz: [
    'yyyyyyyy',
    'ywwwwwwy',
    'ywbbbbwy',
    'ywbbbbwy',
    'ywwwwwwy',
    'ywrrrrwy',
    'yyyyyyyy',
    '.d....d.',
  ],
  poca: [
    '...bbbb...',
    '.bbuuuubb.',
    'bbuucuuubb',
    '.bbuuuubb.',
    '...bbbb...',
  ],
  mastro: [
    '.eeeeYY.',
    '.eyyyYY.',
    '.eeeeYY.',
    '.d......',
    '.d......',
    '.d......',
    '.d......',
    '.d......',
    '.d......',
    'dddd....',
  ],
  degrau: [
    'tttttttt',
    'TTTTTTTT',
    'nnnnnnnn',
    'NNNNNNNN',
  ],
  corrimao: [
    'k......k',
    'gggggggg',
    'g.g..g.g',
    'g.g..g.g',
    'g.g..g.g',
    'd.d..d.d',
  ],
  pilar: [
    '.llllll.',
    '..iiii..',
    '..iwgg..',
    '..iwgg..',
    '..iwgg..',
    '..iwgg..',
    '..iwgg..',
    '.lllllll',
    'gggggggg',
  ],
  lampada: [
    '..wwww..',
    '.wyyyyw.',
    'wyYYYYyw',
    'wyYYYYyw',
    '.wyyyyw.',
    '..gggg..',
    '..dddd..',
  ],
  mureta: [
    'tttttttttttt',
    'TtTtTtTtTtTt',
    'nnnnnnnnnnnn',
    'NnNnNnNnNnNn',
  ],
  violao: [
    '....nn..',
    '....nn..',
    '....Nn..',
    '...nNn..',
    '.tttt...',
    'tTkkTt..',
    'ttkktt..',
    '.tTTt...',
    'tttttt..',
    '.tttt...',
  ],
  pandeiro: [
    '..tttt..',
    '.tkTTkt.',
    'tTwwwwTt',
    'twwwwwwt',
    'twwwwwwt',
    'tTwwwwTt',
    '.tkTTkt.',
    '..tttt..',
  ],
  microfone: [
    '..dddd..',
    '.dggggd.',
    '.dggggd.',
    '..dddd..',
    '...dd...',
    '...dd...',
    '...dd...',
    '..dddd..',
  ],
  alto_falante: [
    'dddddddd',
    'dggggggd',
    'dgdddddg',
    'dgdkkdgd',
    'dgdkkdgd',
    'dgdddddg',
    'dggggggd',
    'dddddddd',
  ],
  panela: [
    'dd....dd',
    '.dggggd.',
    'ddggggdd',
    'dgwggggd',
    'dgggggdd',
    '.dggggd.',
    '..dddd..',
  ],
  saquinho: [
    'ttttttt',
    'tTTTTTt',
    'twwwwwt',
    'twrrrwt',
    'twrwrwt',
    'twrrrwt',
    'twwwwwt',
    'ttttttt',
  ],
  sorvete: [
    '..pp..',
    '.pPPp.',
    'wpwPpw',
    '.wwww.',
    '.wiiw.',
    '..ww..',
  ],
  picole: [
    '.rrrr.',
    'rrRRrr',
    'rrRRrr',
    'rrRRrr',
    'rrRRrr',
    '.rrrr.',
    '..tt..',
    '..tt..',
  ],
  guardanapo: [
    'wwwwww',
    'wiiiiw',
    'wiggiw',
    'wiiiiw',
    'wwwwww',
  ],
  cavalete: [
    '..wwww..',
    '.wbbcgw.',
    '.wrrbyw.',
    '.wwwwww.',
    '.n....n.',
    '.n.nn.n.',
    'n..nn..n',
    'n..nn..n',
  ],
  tinta: [
    '.dddd.',
    'dggggd',
    'rrrrrr',
    'rRRRRr',
    'rrrrrr',
    '.dddd.',
  ],
  balde: [
    'dddddddd',
    '.bbbbbb.',
    '.bubbbb.',
    '.bubbbb.',
    '.bbbbbb.',
    '..bbbb..',
  ],
  pano: [
    '.yyyyyy.',
    'yYyyyyyy',
    'yyyyoyyy',
    'yyyyyyyy',
    '.yoyyyy.',
    '..yyyy..',
  ],
  vassoura: [
    '....n...',
    '....n...',
    '....n...',
    '....n...',
    '....n...',
    '..tttt..',
    '.tTtTtt.',
    '.tTtTtt.',
    '.t.t.t..',
  ],
  pa: [
    '...n....',
    '...n....',
    '...n....',
    '...n....',
    '..ggg...',
    '.gwwgg..',
    '.gwgdg..',
    '..gdd...',
  ],
  luva: [
    '.y.y.y..',
    '.yyyyy..',
    'yyyyyyy.',
    'yyyyyyy.',
    '.yyyyyy.',
    '..oooo..',
  ],
  grafite: [
    'gggggggggggg',
    'gpppbbbccyyg',
    'gpPpbBbccyYg',
    'gpppbbbccyyg',
    'grrrvvvvooog',
    'gggggggggggg',
  ],
  adesivo: [
    'wwwwww',
    'wyyyyw',
    'wyrryw',
    'wyrryw',
    'wyyyyw',
    'wwwwww',
  ],
  madeira: [
    'nnnnnnnn',
    'NnNnNnNn',
    'tttttttt',
    'TtTtTtTt',
    'nnnnnnnn',
  ],
  ferro: [
    'dddddddd',
    'dgggggwd',
    'dggggggd',
    'dddddddd',
    '.d....d.',
  ],
  concreto: [
    'gggggggg',
    'gllllllg',
    'glgllggg',
    'gllllllg',
    'dddddddd',
  ],
  tijolo: [
    'rrRrrRrr',
    'RrrRrrRr',
    'rRrrRrrR',
    'wwwwwwww',
  ],
  papel: [
    '.wwww.',
    'wiiiiw',
    'wiggiw',
    'wiiiiw',
    '.wwww.',
  ],
  vidro: [
    '..cc..',
    '..cc..',
    '.cwcc.',
    '.cwcc.',
    '.cccc.',
    '.cccc.',
    '.cccc.',
  ],
  tampinha: [
    '.dddd.',
    'dyyyyd',
    'dyYYyd',
    'dyyyyd',
    '.dddd.',
  ],
  papelao: [
    'ttttttttt',
    'tTTTTTTTt',
    'tTnnnnnTt',
    'tTTTTTTTt',
    'ttttttttt',
  ],
  coleira: [
    '..rrrr..',
    '.r....r.',
    'r......r',
    'r..yy..r',
    '.r.yy.r.',
    '..rrrr..',
  ],
  formigueiro: [
    '...nn...',
    '..nNNn..',
    '.nNNNNn.',
    'nNNkkNNn',
    'nNNNNNNn',
    'nnnnnnnn',
  ],
  sabia: [
    '..nnn...',
    '.nnnnk..',
    '.nnnnnoo',
    'nnnTTnn.',
    'nnTTTn..',
    '.nTTn...',
    '..oo.oo.',
  ],
  bem_te_vi: [
    '..kkk...',
    '.kwkkk..',
    '.kkkkyy.',
    'nnnyyyk.',
    'nnnyyy..',
    '.nyyn...',
    '..oo.oo.',
  ],
  andorinha: [
    'kk....kk',
    'kkk..kkk',
    '.kkkkkk.',
    '..kwwk..',
    '...kk...',
    '..k..k..',
  ],
  ninho: [
    '..nNn...',
    '.nnNnn..',
    'nNnnNnnn',
    'nnNnnNnn',
    '.nnnnnn.',
    '..nnnn..',
  ],
  pena: [
    '......bb',
    '....bbbc',
    '..bbbbc.',
    '.bbbbc..',
    'bbbcc...',
    'bcc.....',
    'c.......',
  ],
  galho: [
    '.....e..',
    '..e.ne..',
    '..nnn...',
    'nnnn....',
    '.nNnnn..',
    '..NnnnnN',
  ],
  tronco: [
    '.nnnnnnnn.',
    'nNttTTttNn',
    'nNtnnnntNn',
    'nNttTTttNn',
    '.nnnnnnnn.',
  ],
  cogumelo: [
    '..rrrr..',
    '.rwrrwr.',
    'rrrwrrrr',
    'rrrrrrrr',
    '...ii...',
    '...ii...',
    '..iiii..',
  ],
  cipo: [
    '.e......',
    '.ee..e..',
    '..ef.ee.',
    '..eE.e..',
    '...eEe..',
    '...eE...',
    '...e....',
  ],
  portao: [
    'd......d',
    'dgdgdgdg',
    'dgdgdgdg',
    'dgdgdgdg',
    'dgdgdgdg',
    'dgdgdgdg',
    'dgdgdgdg',
    'dddddddd',
  ],
  cadeado: [
    '..gggg..',
    '.g....g.',
    '.g....g.',
    'yyyyyyyy',
    'yYyyyyoy',
    'yyykkyyy',
    'yyyyyyoy',
    '.yyyyyy.',
  ],
  meio_fio: [
    'gggggggggggg',
    'lllllllllllw',
    'ggggggggggdd',
    'dddddddddddd',
  ],
  sarjeta: [
    'dddddddddddd',
    'gdgdgdgdgdgd',
    'ddddddddbbbb',
    'dddddddddddd',
  ],
  calcada: [
    'llllllllllll',
    'wlwlwlwlwlwl',
    'llllllllllll',
    'gggggggggggg',
  ],
  rampa: [
    '.......ll',
    '.....lllg',
    '...llllgg',
    '.lllllggg',
    'llllgggdd',
    'ddddddddd',
  ],
  caminho: [
    'tttt..tt..',
    'tTTt.tTTt.',
    '.tt..tttt.',
    '..tt.tTTt.',
    '.tTTt.tt..',
    '..tt......',
  ],
  pedra: [
    '..gggg..',
    '.gllllg.',
    'glllllgg',
    'ggggggdd',
  ],
  musgo: [
    'e.ee.e.e',
    'eeEeeeEe',
    'EeeEeeee',
    'eEEeEEee',
  ],
  samambaia: [
    '.e..e..e',
    '..e.e.e.',
    'e.eeeee.',
    '.eeEeEe.',
    'eeEeEeEe',
    '..eEEe..',
    '...nn...',
  ],
  margarida: [
    '..w.w...',
    '.wwywwy.',
    '..wywy..',
    '.w.w.w..',
    '...e....',
    '..ee....',
    '...e....',
  ],
  rosa: [
    '..rrr...',
    '.rRrRr..',
    '.rrRrr..',
    '..rrr...',
    '...e.e..',
    '...ee...',
    '...e....',
  ],
  petala: [
    '..pp..',
    '.pPPp.',
    'pPPPPp',
    '.pPPp.',
    '..pp..',
  ],
  abelha: [
    '..ww.ww.',
    '.wkwkw..',
    '.kyyyk..',
    '.kkkkk..',
    '.kyyyk..',
    '..kkk...',
  ],
  borboleta: [
    'bb...vv.',
    'bBb.vVv.',
    'bbbkvvv.',
    '.bBkVv..',
    '..bkvv..',
    '...k....',
  ],
  cigarra: [
    '.gg.gg..',
    'gwgggwg.',
    '.gggggg.',
    '.eeeeee.',
    '..eEEe..',
    '..e..e..',
  ],
  formiga: [
    '.k.kk.k.',
    '..kkkk..',
    '.kk..kk.',
    'k.kkkk.k',
    '..k..k..',
  ],
};
