/**
 * The airport hall behind the arrival card: the fourteen camera objects of the Chegada area, one art pixel per character (`.` is empty).
 * A postcard drawn in the page (ui/arrivalHall.ts), not a room of the world atlas, so these live with the client.
 */
export const HALL_PAL: Record<string, string> = {
  k: '#3a3a50', d: '#565972', g: '#8b8bab', l: '#c6bdd5', i: '#ebe4f2', w: '#f8f8f8',
  r: '#d93232', R: '#9e2b2d', o: '#ed931e', y: '#f8d239', Y: '#fff59a',
  n: '#a9764f', N: '#6b4c2c', t: '#daa463',
  e: '#64b63b', E: '#32675a',
  b: '#4995e3', B: '#3d56d2', c: '#95e3e3', u: '#50a7e8',
};

export const HALL_ART: Record<string, string[]> = {
  mala: [
    '...dd...',
    '..d..d..',
    'bbbbbbbb',
    'bBBBBBBb',
    'bBbbbbBb',
    'bBBBBBBb',
    'bbbbbbbb',
    '.d....d.',
  ],
  passaporte: [
    'BBBBBBB',
    'ByyyyyB',
    'ByyYyyB',
    'ByyyyyB',
    'ByyyyyB',
    'BBBBBBB',
  ],
  esteira: [
    'dddddddddddddddd',
    'kgkgkgkgkgkgkgkg',
    'dddddddddddddddd',
    'g..g..g..g..g..g',
  ],
  mochila: [
    '..dddd..',
    '.d....d.',
    'eeeeeeee',
    'eEEEEEEe',
    'eEddddEe',
    'eEEEEEEe',
    'eEEyyEEe',
    'eeeeeeee',
  ],
  pista: [
    'dddddddddddd',
    'dddddddddddd',
    'dwwdwwdwwdww',
    'dddddddddddd',
    'dddddddddddd',
  ],
  torre: [
    '..bbbbbb..',
    '.bccccccb.',
    '.bcwcwccb.',
    '.bbbbbbbb.',
    '...gggg...',
    '...gwwg...',
    '...gwwg...',
    '...gwwg...',
    '...gwwg...',
    '..gggggg..',
  ],
  ponte: [
    'gggggggggggg',
    'gcccccccccgg',
    'gcwcwcwcwcgg',
    'gcccccccccgg',
    'gggggggggggg',
    '.d........d.',
  ],
  cinto: [
    'dddddddddddd',
    'dggggggggggd',
    'dddddddddyyd',
    '..........yd',
  ],
  asa: [
    '...........ww',
    '.........wwww',
    '.......wwwwww',
    '.....wwwwwwgg',
    '...wwwwwwwgg.',
    'wwwwwwwwggg..',
    'wwwwgggggg...',
  ],
  fone: [
    '..dddddd..',
    '.d......d.',
    'd........d',
    'dd......dd',
    'rr......rr',
    'rr......rr',
  ],
  bilhete: [
    'wwwwwwwwww',
    'wbbbbbwiiw',
    'wwwwwwwiiw',
    'wgggggwiiw',
    'wwwwwwwwww',
  ],
  visto: [
    '.rrrrrrr.',
    'rRRRRRRRr',
    'rRwrrrwRr',
    'rRrrwrrRr',
    'rRwrrrwRr',
    'rRRRRRRRr',
    '.rrrrrrr.',
  ],
  etiqueta: [
    '.kk.....',
    'k..kkkkk',
    'k..kwwwk',
    '.kkkwbwk',
    '....kwwk',
    '.....kkk',
  ],
  turbina: [
    '..dddddd..',
    '.dgggggggd',
    'dgdddddddg',
    'dgdkkkkdgd',
    'dgdkwwkdgd',
    'dgdkkkkdgd',
    'dgdddddddg',
    '.dgggggggd',
    '..dddddd..',
  ],
};
