/**
 * Where the objects and signs added for the language diary catalog stand. A camera word anchors `d_<word>`, a reading word `s_<word>`
 * (a sign you read), and each placement is a non-blocking prop (and, for a sign, a hotspot) next to the thing it belongs to. Positions
 * come from a one-off pass that put each item on the free tile nearest its anchor; two small items may share a tile (`ox` nudges one
 * of them sideways). Every Portuguese string here is needs_br and comes from the catalog: a sign prints the word, nothing more.
 */
import type { RoomId } from './types.js';

export interface DiaryPlacement {
  id: string;
  room: RoomId;
  x: number;
  y: number;
  w?: number;
  h?: number;
  /** Pixels the sprite is nudged sideways inside its tile (two small items on one tile). */
  ox?: number;
  /** Manifest sprite key. */
  art: string;
  /** A reading word: the sign text, and the hotspot that reads it. */
  sign?: { pt: string; en: string };
}

export const DIARY_PLACEMENTS: DiaryPlacement[] = [
  { id: 'd_caminhao', room: 'rua_leste', x: 1, y: 11, w: 3, art: 'diary/caminhao' },
  { id: 'd_ambulancia', room: 'rua_leste', x: 10, y: 11, w: 3, art: 'diary/ambulancia' },
  { id: 'd_esquina', room: 'rua_leste', x: 14, y: 7, art: 'diary/esquina' },
  { id: 'd_macaneta', room: 'rua_leste', x: 13, y: 5, art: 'diary/macaneta' },
  { id: 'd_retrovisor', room: 'rua_leste', x: 13, y: 13, art: 'diary/retrovisor' },
  { id: 'd_porta_malas', room: 'rua_leste', x: 14, y: 14, art: 'diary/porta_malas' },
  { id: 'd_farol', room: 'rua_leste', x: 15, y: 14, art: 'diary/farol' },
  { id: 'd_volante', room: 'rua_leste', x: 12, y: 13, art: 'diary/volante' },
  { id: 'd_buzina', room: 'rua_leste', x: 16, y: 14, art: 'diary/buzina' },
  { id: 'd_cone', room: 'rua_leste', x: 8, y: 14, art: 'diary/cone' },
  { id: 'd_tapume', room: 'rua_leste', x: 7, y: 14, art: 'diary/tapume' },
  { id: 'd_andaime', room: 'rua_leste', x: 9, y: 13, art: 'diary/andaime' },
  { id: 'd_escada', room: 'rua_leste', x: 10, y: 14, art: 'diary/escada' },
  { id: 'd_cruzamento', room: 'rua_leste', x: 3, y: 7, art: 'diary/cruzamento' },
  { id: 'd_skate', room: 'rua_leste', x: 5, y: 7, art: 'diary/skate' },
  { id: 'd_patinete', room: 'rua_leste', x: 9, y: 7, art: 'diary/patinete' },
  { id: 's_pare', room: 'rua_leste', x: 1, y: 6, w: 2, art: 'diary/sign_pare', sign: { pt: "PARE", en: "Stop" } },
  { id: 's_obra', room: 'rua_leste', x: 7, y: 13, w: 2, art: 'diary/sign_obra', sign: { pt: "OBRAS", en: "Road work" } },
  { id: 's_sentido', room: 'rua_leste', x: 8, y: 6, w: 4, art: 'diary/sign_sentido', sign: { pt: "SENTIDO ÚNICO", en: "Direction" } },
  { id: 's_farmacia', room: 'rua_leste', x: 2, y: 5, w: 3, art: 'diary/sign_farmacia', sign: { pt: "FARMÁCIA", en: "Pharmacy" } },
  { id: 's_loterica', room: 'rua_leste', x: 6, y: 5, w: 3, art: 'diary/sign_loterica', sign: { pt: "LOTÉRICA", en: "Lottery shop" } },
  { id: 's_acougue', room: 'rua_leste', x: 9, y: 5, w: 2, art: 'diary/sign_acougue', sign: { pt: "AÇOUGUE", en: "Butcher" } },
  { id: 's_mercado', room: 'rua_leste', x: 10, y: 7, w: 2, art: 'diary/sign_mercado', sign: { pt: "MERCADO", en: "Market" } },
  { id: 's_chaveiro', room: 'rua_leste', x: 14, y: 5, w: 3, art: 'diary/sign_chaveiro', sign: { pt: "CHAVEIRO", en: "Locksmith" } },
  { id: 's_ladeira', room: 'rua_leste', x: 17, y: 5, w: 2, art: 'diary/sign_ladeira', sign: { pt: "LADEIRA", en: "Hill street" } },
  { id: 's_travessa', room: 'rua_leste', x: 1, y: 12, w: 3, art: 'diary/sign_travessa', sign: { pt: "TRAVESSA", en: "Side lane" } },
  { id: 'd_pombo', room: 'praca', x: 15, y: 9, art: 'critters/pigeon' },
  { id: 'd_paralelepipedo', room: 'praca', x: 16, y: 8, art: 'diary/paralelepipedo' },
  { id: 'd_grama', room: 'praca', x: 5, y: 8, art: 'decals/gtuft_0' },
  { id: 'd_folha', room: 'praca', x: 4, y: 2, art: 'diary/folha' },
  { id: 'd_relogio', room: 'praca', x: 13, y: 8, art: 'diary/relogio' },
  { id: 'd_estatua', room: 'praca', x: 9, y: 12, art: 'diary/estatua' },
  { id: 'd_guarda_sol', room: 'praca', x: 12, y: 16, art: 'diary/guarda_sol' },
  { id: 'd_cesta', room: 'praca', x: 23, y: 20, art: 'diary/cesta' },
  { id: 'd_garrafa', room: 'praca', x: 18, y: 16, art: 'diary/garrafa' },
  { id: 'd_copo', room: 'praca', x: 19, y: 22, art: 'diary/copo' },
  { id: 'd_lata', room: 'praca', x: 13, y: 18, art: 'diary/lata' },
  { id: 'd_bolsa', room: 'praca', x: 5, y: 19, art: 'diary/bolsa' },
  { id: 'd_moeda', room: 'praca', x: 16, y: 9, art: 'diary/moeda' },
  { id: 'd_cedula', room: 'praca', x: 25, y: 8, art: 'diary/cedula' },
  { id: 'd_celular', room: 'praca', x: 11, y: 5, art: 'diary/celular' },
  { id: 'd_folheto', room: 'praca', x: 12, y: 1, art: 'diary/folheto' },
  { id: 'd_cartaz', room: 'praca', x: 11, y: 2, art: 'diary/cartaz' },
  { id: 'd_bueiro', room: 'praca', x: 16, y: 19, art: 'decals/manhole' },
  { id: 'd_poca', room: 'praca', x: 17, y: 18, art: 'diary/poca' },
  { id: 'd_mastro', room: 'praca', x: 25, y: 3, art: 'diary/mastro' },
  { id: 'd_degrau', room: 'praca', x: 25, y: 7, art: 'diary/degrau' },
  { id: 'd_corrimao', room: 'praca', x: 24, y: 3, art: 'diary/corrimao' },
  { id: 'd_pilar', room: 'praca', x: 26, y: 3, art: 'diary/pilar' },
  { id: 'd_lampada', room: 'praca', x: 19, y: 8, art: 'diary/lampada' },
  { id: 'd_fio', room: 'praca', x: 8, y: 13, w: 8, art: 'props/fios_8' },
  { id: 'd_mureta', room: 'praca', x: 8, y: 10, art: 'diary/mureta' },
  { id: 'd_violao', room: 'praca', x: 24, y: 7, art: 'diary/violao' },
  { id: 'd_pandeiro', room: 'praca', x: 26, y: 7, art: 'diary/pandeiro' },
  { id: 'd_microfone', room: 'praca', x: 23, y: 3, art: 'diary/microfone' },
  { id: 'd_alto_falante', room: 'praca', x: 23, y: 7, art: 'diary/alto_falante' },
  { id: 'd_panela', room: 'praca', x: 18, y: 20, art: 'diary/panela' },
  { id: 'd_saquinho', room: 'praca', x: 20, y: 20, art: 'diary/saquinho' },
  { id: 'd_sorvete', room: 'praca', x: 25, y: 10, art: 'diary/sorvete' },
  { id: 'd_picole', room: 'praca', x: 24, y: 8, art: 'diary/picole' },
  { id: 'd_guardanapo', room: 'praca', x: 21, y: 16, art: 'diary/guardanapo' },
  { id: 'd_cavalete', room: 'praca', x: 8, y: 15, art: 'diary/cavalete' },
  { id: 'd_tinta', room: 'praca', x: 8, y: 14, art: 'diary/tinta' },
  { id: 'd_balde', room: 'praca', x: 12, y: 14, art: 'diary/balde' },
  { id: 'd_pano', room: 'praca', x: 13, y: 14, art: 'diary/pano' },
  { id: 'd_vassoura', room: 'praca', x: 30, y: 18, art: 'diary/vassoura' },
  { id: 'd_pa', room: 'praca', x: 18, y: 14, art: 'diary/pa' },
  { id: 'd_luva', room: 'praca', x: 19, y: 14, art: 'diary/luva' },
  { id: 'd_grafite', room: 'praca', x: 1, y: 11, art: 'diary/grafite' },
  { id: 'd_adesivo', room: 'praca', x: 20, y: 13, art: 'diary/adesivo' },
  { id: 'd_madeira', room: 'praca', x: 12, y: 5, art: 'diary/madeira' },
  { id: 'd_ferro', room: 'praca', x: 13, y: 16, art: 'diary/ferro' },
  { id: 'd_concreto', room: 'praca', x: 16, y: 13, art: 'diary/concreto' },
  { id: 'd_tijolo', room: 'praca', x: 15, y: 17, art: 'diary/tijolo' },
  { id: 'd_papel', room: 'praca', x: 19, y: 5, art: 'diary/papel' },
  { id: 'd_vidro', room: 'praca', x: 18, y: 6, art: 'diary/vidro' },
  { id: 'd_tampinha', room: 'praca', x: 19, y: 16, art: 'diary/tampinha' },
  { id: 'd_papelao', room: 'praca', x: 12, y: 19, art: 'diary/papelao' },
  { id: 'd_coleira', room: 'praca', x: 3, y: 20, art: 'diary/coleira' },
  { id: 'd_tigela', room: 'praca', x: 4, y: 21, art: 'decals/tigela' },
  { id: 'd_formigueiro', room: 'praca', x: 9, y: 19, art: 'diary/formigueiro' },
  { id: 'd_sabia', room: 'praca', x: 9, y: 2, art: 'diary/sabia' },
  { id: 'd_bem_te_vi', room: 'praca', x: 27, y: 2, art: 'diary/bem_te_vi' },
  { id: 'd_andorinha', room: 'praca', x: 11, y: 7, art: 'diary/andorinha' },
  { id: 'd_ninho', room: 'praca', x: 5, y: 2, art: 'diary/ninho' },
  { id: 'd_pena', room: 'praca', x: 14, y: 5, art: 'diary/pena' },
  { id: 'd_galho', room: 'praca', x: 10, y: 15, art: 'diary/galho' },
  { id: 'd_tronco', room: 'praca', x: 27, y: 15, art: 'diary/tronco' },
  { id: 'd_cogumelo', room: 'praca', x: 6, y: 10, art: 'diary/cogumelo' },
  { id: 'd_cipo', room: 'praca', x: 1, y: 12, art: 'diary/cipo' },
  { id: 'd_portao', room: 'praca', x: 30, y: 9, art: 'diary/portao' },
  { id: 'd_cadeado', room: 'praca', x: 30, y: 8, art: 'diary/cadeado' },
  { id: 'd_meio_fio', room: 'praca', x: 13, y: 1, art: 'diary/meio_fio' },
  { id: 'd_sarjeta', room: 'praca', x: 14, y: 1, art: 'diary/sarjeta' },
  { id: 'd_calcada', room: 'praca', x: 13, y: 5, art: 'diary/calcada' },
  { id: 'd_rampa', room: 'praca', x: 29, y: 9, art: 'diary/rampa' },
  { id: 'd_caminho', room: 'praca', x: 15, y: 18, art: 'diary/caminho' },
  { id: 'd_pedra', room: 'praca', x: 14, y: 18, art: 'diary/pedra' },
  { id: 'd_musgo', room: 'praca', x: 14, y: 9, art: 'diary/musgo' },
  { id: 'd_samambaia', room: 'praca', x: 11, y: 15, art: 'diary/samambaia' },
  { id: 'd_margarida', room: 'praca', x: 14, y: 15, art: 'diary/margarida' },
  { id: 'd_rosa', room: 'praca', x: 17, y: 15, art: 'diary/rosa' },
  { id: 'd_petala', room: 'praca', x: 20, y: 15, art: 'diary/petala' },
  { id: 'd_abelha', room: 'praca', x: 14, y: 14, art: 'diary/abelha' },
  { id: 'd_borboleta', room: 'praca', x: 17, y: 14, art: 'diary/borboleta' },
  { id: 'd_cigarra', room: 'praca', x: 22, y: 8, art: 'diary/cigarra' },
  { id: 'd_formiga', room: 'praca', x: 9, y: 18, art: 'diary/formiga' },
  { id: 's_banheiro', room: 'praca', x: 27, y: 21, w: 3, art: 'diary/sign_banheiro', sign: { pt: "BANHEIRO", en: "Restroom" } },
  { id: 's_reciclagem', room: 'praca', x: 17, y: 7, w: 3, art: 'diary/sign_reciclagem', sign: { pt: "RECICLAGEM", en: "Recycling" } },
  { id: 's_mapa', room: 'praca', x: 12, y: 3, w: 2, art: 'diary/sign_mapa', sign: { pt: "MAPA", en: "Map" } },
  { id: 's_horario', room: 'praca', x: 10, y: 1, w: 2, art: 'diary/sign_horario', sign: { pt: "HORÁRIO", en: "Hours" } },
  { id: 's_entrada', room: 'praca', x: 29, y: 10, w: 2, art: 'diary/sign_entrada', sign: { pt: "ENTRADA", en: "Entrance" } },
  { id: 's_fechado', room: 'praca', x: 11, y: 4, w: 2, art: 'diary/sign_fechado', sign: { pt: "FECHADO", en: "Closed" } },
  { id: 's_cuidado', room: 'praca', x: 17, y: 9, w: 2, art: 'diary/sign_cuidado', sign: { pt: "CUIDADO", en: "Caution" } },
  { id: 's_wifi', room: 'praca', x: 13, y: 4, w: 2, art: 'diary/sign_wifi', sign: { pt: "WIFI", en: "Wifi" } },
  { id: 's_emergencia', room: 'praca', x: 14, y: 2, w: 3, art: 'diary/sign_emergencia', sign: { pt: "EMERGÊNCIA", en: "Emergency" } },
  { id: 's_informacao', room: 'praca', x: 14, y: 3, w: 3, art: 'diary/sign_informacao', sign: { pt: "INFORMAÇÃO", en: "Information" } },
  { id: 'd_moto', room: 'rua', x: 8, y: 12, w: 2, art: 'vehicles/park_moto_e' },
  { id: 'd_van', room: 'rua', x: 2, y: 13, w: 4, h: 2, art: 'vehicles/park_kombi_w' },
  { id: 'd_semaforo', room: 'rua', x: 19, y: 7, art: 'diary/semaforo' },
  { id: 'd_muro', room: 'rua', x: 19, y: 6, art: 'diary/muro' },
  { id: 'd_interfone', room: 'rua', x: 13, y: 5, art: 'diary/interfone' },
  { id: 'd_campainha', room: 'rua', x: 14, y: 5, art: 'diary/campainha' },
  { id: 'd_capacho', room: 'rua', x: 5, y: 6, art: 'props/doormat' },
  { id: 'd_varanda', room: 'rua', x: 16, y: 5, art: 'diary/varanda' },
  { id: 'd_grade', room: 'rua', x: 18, y: 5, art: 'diary/grade' },
  { id: 'd_ar_condicionado', room: 'rua', x: 20, y: 5, art: 'diary/ar_condicionado' },
  { id: 'd_antena', room: 'rua', x: 1, y: 5, art: 'diary/antena' },
  { id: 'd_lombada', room: 'rua', x: 16, y: 11, art: 'diary/lombada' },
  { id: 'd_encomenda', room: 'rua', x: 13, y: 6, art: 'diary/encomenda' },
  { id: 'd_envelope', room: 'rua', x: 12, y: 7, art: 'diary/envelope' },
  { id: 'd_selo', room: 'rua', x: 13, y: 7, art: 'diary/selo' },
  { id: 'd_tenis', room: 'rua', x: 17, y: 6, art: 'diary/tenis' },
  { id: 'd_guarda_chuva', room: 'rua', x: 9, y: 7, art: 'diary/guarda_chuva' },
  { id: 'd_capacete', room: 'rua', x: 8, y: 13, art: 'diary/capacete' },
  { id: 'd_pneu', room: 'rua', x: 11, y: 12, art: 'diary/pneu' },
  { id: 'd_guidao', room: 'rua', x: 15, y: 6, art: 'diary/guidao' },
  { id: 'd_pedal', room: 'rua', x: 14, y: 7, art: 'diary/pedal' },
  { id: 's_ciclovia', room: 'rua', x: 4, y: 11, w: 3, art: 'diary/sign_ciclovia', sign: { pt: "CICLOVIA", en: "Bike lane" } },
  { id: 's_correio', room: 'rua', x: 17, y: 12, w: 3, art: 'diary/sign_correio', sign: { pt: "CORREIOS", en: "Post office" } },
  { id: 's_devagar', room: 'rua', x: 18, y: 11, w: 2, art: 'diary/sign_devagar', sign: { pt: "DEVAGAR", en: "Slow" } },
  { id: 's_salao', room: 'rua', x: 5, y: 5, w: 2, art: 'diary/sign_salao', sign: { pt: "SALÃO", en: "Salon" } },
  { id: 's_barbearia', room: 'rua', x: 9, y: 5, w: 3, art: 'diary/sign_barbearia', sign: { pt: "BARBEARIA", en: "Barbershop" } },
  { id: 's_lavanderia', room: 'rua', x: 17, y: 13, w: 3, art: 'diary/sign_lavanderia', sign: { pt: "LAVANDERIA", en: "Laundromat" } },
  { id: 's_igreja', room: 'rua', x: 2, y: 5, w: 2, art: 'diary/sign_igreja', sign: { pt: "IGREJA", en: "Church" } },
  { id: 'd_abacaxi', room: 'feira', x: 7, y: 7, art: 'diary/abacaxi' },
  { id: 'd_mamao', room: 'feira', x: 6, y: 7, art: 'diary/mamao' },
  { id: 'd_maracuja', room: 'feira', x: 8, y: 7, art: 'diary/maracuja' },
  { id: 'd_limao', room: 'feira', x: 7, y: 8, art: 'diary/limao' },
  { id: 'd_abacate', room: 'feira', x: 6, y: 6, art: 'diary/abacate' },
  { id: 'd_uva', room: 'feira', x: 8, y: 6, art: 'diary/uva' },
  { id: 'd_morango', room: 'feira', x: 6, y: 8, art: 'diary/morango' },
  { id: 'd_goiaba', room: 'feira', x: 8, y: 8, art: 'diary/goiaba' },
  { id: 'd_tangerina', room: 'feira', x: 5, y: 7, art: 'diary/tangerina' },
  { id: 'd_acerola', room: 'feira', x: 9, y: 7, art: 'diary/acerola' },
  { id: 'd_caju', room: 'feira', x: 7, y: 9, art: 'diary/caju' },
  { id: 'd_pitaya', room: 'feira', x: 6, y: 5, art: 'diary/pitaya' },
  { id: 'd_milho', room: 'feira', x: 13, y: 7, art: 'diary/milho' },
  { id: 'd_batata', room: 'feira', x: 12, y: 7, art: 'diary/batata' },
  { id: 'd_cenoura', room: 'feira', x: 14, y: 7, art: 'diary/cenoura' },
  { id: 'd_beterraba', room: 'feira', x: 13, y: 8, art: 'diary/beterraba' },
  { id: 'd_cebola', room: 'feira', x: 12, y: 6, art: 'diary/cebola' },
  { id: 'd_alho', room: 'feira', x: 14, y: 6, art: 'diary/alho' },
  { id: 'd_pimentao', room: 'feira', x: 12, y: 8, art: 'diary/pimentao' },
  { id: 'd_pepino', room: 'feira', x: 14, y: 8, art: 'diary/pepino' },
  { id: 'd_abobrinha', room: 'feira', x: 11, y: 7, art: 'diary/abobrinha' },
  { id: 'd_chuchu', room: 'feira', x: 15, y: 7, art: 'diary/chuchu' },
  { id: 'd_mandioca', room: 'feira', x: 13, y: 9, art: 'diary/mandioca' },
  { id: 'd_couve', room: 'feira', x: 12, y: 5, art: 'diary/couve' },
  { id: 'd_brocolis', room: 'feira', x: 11, y: 6, art: 'diary/brocolis' },
  { id: 'd_coentro', room: 'feira', x: 15, y: 6, art: 'diary/coentro' },
  { id: 'd_gengibre', room: 'feira', x: 11, y: 8, art: 'diary/gengibre' },
  { id: 'd_quiabo', room: 'feira', x: 15, y: 8, art: 'diary/quiabo' },
  { id: 'd_jilo', room: 'feira', x: 12, y: 9, art: 'diary/jilo' },
  { id: 'd_berinjela', room: 'feira', x: 14, y: 9, art: 'diary/berinjela' },
  { id: 'd_vagem', room: 'feira', x: 11, y: 5, art: 'diary/vagem' },
  { id: 'd_cana', room: 'feira', x: 7, y: 15, art: 'diary/cana' },
  { id: 'd_lona', room: 'feira', x: 6, y: 15, art: 'diary/lona' },
  { id: 'd_oleo', room: 'feira', x: 8, y: 15, art: 'diary/oleo' },
  { id: 'd_molho', room: 'feira', x: 7, y: 16, art: 'diary/molho' },
  { id: 'd_pimenta', room: 'feira', x: 6, y: 14, art: 'diary/pimenta' },
  { id: 'd_gelo', room: 'feira', x: 8, y: 14, art: 'diary/gelo' },
  { id: 'd_canudo', room: 'feira', x: 6, y: 16, art: 'diary/canudo' },
  { id: 'd_girassol', room: 'feira', x: 13, y: 15, art: 'diary/girassol' },
  { id: 'd_laco', room: 'feira', x: 12, y: 15, art: 'diary/laco' },
  { id: 'd_bacia', room: 'feira', x: 14, y: 15, art: 'diary/bacia' },
  { id: 'd_sacola', room: 'feira', x: 10, y: 3, art: 'diary/sacola' },
  { id: 'd_giz', room: 'feira', x: 10, y: 5, art: 'diary/giz' },
  { id: 'd_engradado', room: 'feira', x: 4, y: 11, art: 'diary/engradado' },
  { id: 'd_feirante', room: 'feira', x: 19, y: 5, art: 'diary/feirante' },
  { id: 's_organico', room: 'feira', x: 3, y: 3, w: 3, art: 'diary/sign_organico', sign: { pt: "ORGÂNICO", en: "Organic" } },
  { id: 's_quilo', room: 'feira', x: 9, y: 6, w: 2, art: 'diary/sign_quilo', sign: { pt: "R$ / KG", en: "Kilo" } },
  { id: 's_duzia', room: 'feira', x: 15, y: 11, w: 2, art: 'diary/sign_duzia', sign: { pt: "DÚZIA", en: "Dozen" } },
  { id: 's_unidade', room: 'feira', x: 9, y: 13, w: 2, art: 'diary/sign_unidade', sign: { pt: "UNIDADE", en: "Each" } },
  { id: 'd_forno', room: 'padaria', x: 8, y: 0, ox: -4, art: 'diary/forno' },
  { id: 'd_chapa', room: 'padaria', x: 9, y: 0, ox: -4, art: 'diary/chapa' },
  { id: 'd_geladeira', room: 'padaria', x: 0, y: 0, ox: -4, art: 'diary/geladeira' },
  { id: 'd_freezer', room: 'padaria', x: 1, y: 0, ox: -4, art: 'diary/freezer' },
  { id: 'd_prateleira', room: 'padaria', x: 4, y: 0, ox: -4, art: 'diary/prateleira' },
  { id: 'd_cafeteira', room: 'padaria', x: 5, y: 1, ox: -4, art: 'diary/cafeteira' },
  { id: 'd_liquidificador', room: 'padaria', x: 6, y: 1, ox: -4, art: 'diary/liquidificador' },
  { id: 'd_pao', room: 'padaria', x: 2, y: 1, ox: -4, art: 'diary/pao' },
  { id: 'd_torrada', room: 'padaria', x: 7, y: 1, ox: -4, art: 'diary/torrada' },
  { id: 'd_manteiga', room: 'padaria', x: 4, y: 1, ox: -4, art: 'diary/manteiga' },
  { id: 'd_requeijao', room: 'padaria', x: 5, y: 0, ox: -4, art: 'diary/requeijao' },
  { id: 'd_presunto', room: 'padaria', x: 6, y: 0, ox: -4, art: 'diary/presunto' },
  { id: 'd_ovo', room: 'padaria', x: 7, y: 0, ox: -4, art: 'diary/ovo' },
  { id: 'd_leite', room: 'padaria', x: 3, y: 0, ox: -4, art: 'diary/leite' },
  { id: 'd_faca', room: 'padaria', x: 8, y: 1, ox: -4, art: 'diary/faca' },
  { id: 'd_tabua', room: 'padaria', x: 9, y: 1, ox: -4, art: 'diary/tabua' },
  { id: 'd_avental', room: 'padaria', x: 0, y: 1, ox: -4, art: 'diary/avental' },
  { id: 'd_touca', room: 'padaria', x: 1, y: 1, ox: -4, art: 'diary/touca' },
  { id: 'd_jarra', room: 'padaria', x: 2, y: 0, ox: -4, art: 'diary/jarra' },
  { id: 'd_xicara', room: 'padaria', x: 3, y: 5, ox: -4, art: 'diary/xicara' },
  { id: 'd_pires', room: 'padaria', x: 3, y: 5, ox: 4, art: 'diary/pires' },
  { id: 'd_acucar', room: 'padaria', x: 7, y: 5, ox: -4, art: 'diary/acucar' },
  { id: 'd_colher', room: 'padaria', x: 7, y: 5, ox: 4, art: 'diary/colher' },
  { id: 'd_bandeja', room: 'padaria', x: 2, y: 1, ox: 4, art: 'diary/bandeja' },
  { id: 'd_comanda', room: 'padaria', x: 4, y: 3, ox: -4, art: 'diary/comanda' },
  { id: 'd_ficha', room: 'padaria', x: 2, y: 3, ox: -4, art: 'diary/ficha' },
  { id: 'd_sineta', room: 'padaria', x: 5, y: 4, ox: -4, art: 'diary/sineta' },
  { id: 'd_gaveta', room: 'padaria', x: 0, y: 1, ox: 4, art: 'diary/gaveta' },
  { id: 'd_maquininha', room: 'padaria', x: 0, y: 3, ox: -4, art: 'diary/maquininha' },
  { id: 'd_embalagem', room: 'padaria', x: 8, y: 4, ox: -4, art: 'diary/embalagem' },
  { id: 'd_sabonete', room: 'padaria', x: 9, y: 7, ox: -4, art: 'diary/sabonete' },
  { id: 'd_detergente', room: 'padaria', x: 9, y: 7, ox: 4, art: 'diary/detergente' },
  { id: 'd_esponja', room: 'padaria', x: 9, y: 6, ox: -4, art: 'diary/esponja' },
  { id: 's_desconto', room: 'padaria', x: 2, y: 4, w: 3, art: 'diary/sign_desconto', sign: { pt: "DESCONTO", en: "Discount" } },
  { id: 's_promocao', room: 'padaria', x: 4, y: 7, w: 3, art: 'diary/sign_promocao', sign: { pt: "PROMOÇÃO", en: "Special offer" } },
  { id: 'd_fogao', room: 'kitnet', x: 0, y: 0, ox: -4, art: 'diary/fogao' },
  { id: 'd_pia', room: 'kitnet', x: 3, y: 0, ox: -4, art: 'diary/pia' },
  { id: 'd_torneira', room: 'kitnet', x: 3, y: 0, ox: 4, art: 'diary/torneira' },
  { id: 'd_frigideira', room: 'kitnet', x: 3, y: 1, ox: -4, art: 'diary/frigideira' },
  { id: 'd_tampa', room: 'kitnet', x: 3, y: 1, ox: 4, art: 'diary/tampa' },
  { id: 'd_micro_ondas', room: 'kitnet', x: 4, y: 0, ox: -4, art: 'diary/micro_ondas' },
  { id: 'd_chaleira', room: 'kitnet', x: 4, y: 1, ox: -4, art: 'diary/chaleira' },
  { id: 'd_prato', room: 'kitnet', x: 2, y: 1, ox: -4, art: 'diary/prato' },
  { id: 'd_garfo', room: 'kitnet', x: 1, y: 1, ox: -4, art: 'diary/garfo' },
  { id: 'd_sabao', room: 'kitnet', x: 0, y: 1, ox: -4, art: 'diary/sabao' },
  { id: 'd_racao', room: 'kitnet', x: 5, y: 0, ox: -4, art: 'diary/racao' },
  { id: 'd_pote', room: 'kitnet', x: 5, y: 1, ox: -4, art: 'diary/pote' },
  { id: 'd_travesseiro', room: 'kitnet', x: 6, y: 0, ox: -4, art: 'diary/travesseiro' },
  { id: 'd_fronha', room: 'kitnet', x: 6, y: 0, ox: 4, art: 'diary/fronha' },
  { id: 'd_lencol', room: 'kitnet', x: 7, y: 0, ox: -4, art: 'diary/lencol' },
  { id: 'd_cobertor', room: 'kitnet', x: 7, y: 0, ox: 4, art: 'diary/cobertor' },
  { id: 'd_edredom', room: 'kitnet', x: 5, y: 1, ox: 4, art: 'diary/edredom' },
  { id: 'd_colchao', room: 'kitnet', x: 5, y: 2, ox: -4, art: 'diary/colchao' },
  { id: 'd_abajur', room: 'kitnet', x: 5, y: 2, ox: 4, art: 'diary/abajur' },
  { id: 'd_despertador', room: 'kitnet', x: 5, y: 3, ox: -4, art: 'diary/despertador' },
  { id: 'd_oculos', room: 'kitnet', x: 6, y: 3, ox: -4, art: 'diary/oculos' },
  { id: 'd_cabide', room: 'kitnet', x: 7, y: 3, ox: -4, art: 'diary/cabide' },
  { id: 'd_guarda_roupa', room: 'kitnet', x: 5, y: 0, ox: 4, art: 'diary/guarda_roupa' },
  { id: 'd_comoda', room: 'kitnet', x: 4, y: 0, ox: 4, art: 'diary/comoda' },
  { id: 'd_cortina', room: 'kitnet', x: 4, y: 1, ox: 4, art: 'diary/cortina' },
  { id: 'd_espelho', room: 'kitnet', x: 2, y: 3, ox: -4, art: 'diary/espelho' },
  { id: 'd_chinelo', room: 'kitnet', x: 1, y: 4, ox: -4, art: 'diary/chinelo' },
  { id: 'd_chuveiro', room: 'kitnet', x: 7, y: 6, ox: -4, art: 'diary/chuveiro' },
  { id: 'd_box', room: 'kitnet', x: 7, y: 7, ox: -4, art: 'diary/box' },
  { id: 'd_toalha', room: 'kitnet', x: 7, y: 6, ox: 4, art: 'diary/toalha' },
  { id: 'd_xampu', room: 'kitnet', x: 6, y: 7, ox: -4, art: 'diary/xampu' },
  { id: 'd_escova', room: 'kitnet', x: 6, y: 6, ox: -4, art: 'diary/escova' },
  { id: 'd_creme', room: 'kitnet', x: 7, y: 5, ox: -4, art: 'diary/creme' },
  { id: 'd_pente', room: 'kitnet', x: 6, y: 5, ox: -4, art: 'diary/pente' },
  { id: 'd_perfume', room: 'kitnet', x: 5, y: 6, ox: -4, art: 'diary/perfume' },
  { id: 'd_varal', room: 'kitnet', x: 3, y: 7, ox: -4, art: 'diary/varal' },
  { id: 'd_pregador', room: 'kitnet', x: 4, y: 7, ox: -4, art: 'diary/pregador' },
  { id: 'd_tomada', room: 'kitnet', x: 2, y: 2, ox: -4, art: 'diary/tomada' },
  { id: 'd_interruptor', room: 'kitnet', x: 2, y: 3, ox: 4, art: 'diary/interruptor' },
  { id: 'd_carregador', room: 'kitnet', x: 3, y: 2, ox: -4, art: 'diary/carregador' },
  { id: 'd_extensao', room: 'kitnet', x: 4, y: 2, ox: -4, art: 'diary/extensao' },
  { id: 'd_retrato', room: 'kitnet', x: 5, y: 3, ox: 4, art: 'diary/retrato' },
  { id: 'd_chave', room: 'kitnet', x: 1, y: 4, ox: 4, art: 'diary/chave' },
  { id: 's_recado', room: 'kitnet', x: 0, y: 2, w: 2, art: 'diary/sign_recado', sign: { pt: "RECADO", en: "Note" } },
  { id: 's_lista', room: 'kitnet', x: 3, y: 3, w: 2, art: 'diary/sign_lista', sign: { pt: "LISTA", en: "List" } },
  { id: 's_conta', room: 'kitnet', x: 0, y: 3, w: 2, art: 'diary/sign_conta', sign: { pt: "CONTA", en: "Bill" } },
  { id: 'bandeira_br', room: 'academia', x: 10, y: 0, ox: -4, art: 'props/bandeira_br' },
  { id: 'd_cronometro', room: 'academia', x: 8, y: 3, ox: -4, art: 'diary/cronometro' },
  { id: 'd_apito', room: 'academia', x: 7, y: 5, ox: -4, art: 'diary/apito' },
  { id: 'd_prancheta', room: 'academia', x: 9, y: 5, ox: -4, art: 'diary/prancheta' },
  { id: 'd_medalha', room: 'academia', x: 10, y: 3, ox: -4, art: 'diary/medalha' },
  { id: 'd_trofeu', room: 'academia', x: 10, y: 5, ox: -4, art: 'diary/trofeu' },
  { id: 'd_corda', room: 'academia', x: 0, y: 4, ox: -4, art: 'diary/corda' },
  { id: 'd_armario', room: 'academia', x: 0, y: 8, ox: -4, art: 'diary/armario' },
  { id: 'd_recepcao', room: 'academia', x: 10, y: 6, ox: -4, art: 'diary/recepcao' },
  { id: 'd_computador', room: 'academia', x: 10, y: 6, ox: 4, art: 'diary/computador' },
  { id: 'd_podio', room: 'academia', x: 5, y: 6, ox: -4, art: 'diary/podio' },
  { id: 'd_meia', room: 'academia', x: 5, y: 8, ox: -4, art: 'diary/meia' },
  { id: 'd_squeeze', room: 'academia', x: 10, y: 8, ox: -4, art: 'diary/squeeze' },
  { id: 'd_isotonico', room: 'academia', x: 10, y: 8, ox: 4, art: 'diary/isotonico' },
  { id: 's_extintor', room: 'academia', x: 8, y: 7, w: 3, art: 'diary/sign_extintor', sign: { pt: "EXTINTOR", en: "Fire extinguisher" } },
  { id: 's_presenca', room: 'academia', x: 0, y: 3, w: 3, art: 'diary/sign_presenca', sign: { pt: "PRESENÇA", en: "Attendance" } },
  { id: 'd_lapis', room: 'escola', x: 4, y: 2, ox: -4, art: 'diary/lapis' },
  { id: 'd_caneta', room: 'escola', x: 4, y: 2, ox: 4, art: 'diary/caneta' },
  { id: 'd_borracha', room: 'escola', x: 3, y: 3, ox: -4, art: 'diary/borracha' },
  { id: 'd_caderno', room: 'escola', x: 3, y: 3, ox: 4, art: 'diary/caderno' },
  { id: 'd_livro', room: 'escola', x: 5, y: 3, ox: -4, art: 'diary/livro' },
  { id: 'd_estojo', room: 'escola', x: 5, y: 3, ox: 4, art: 'diary/estojo' },
  { id: 'd_apontador', room: 'escola', x: 6, y: 4, ox: -4, art: 'diary/apontador' },
  { id: 'd_regua', room: 'escola', x: 6, y: 4, ox: 4, art: 'diary/regua' },
  { id: 'd_tesoura', room: 'escola', x: 5, y: 5, ox: -4, art: 'diary/tesoura' },
  { id: 'd_cola', room: 'escola', x: 5, y: 5, ox: 4, art: 'diary/cola' },
  { id: 'd_apagador', room: 'escola', x: 1, y: 0, ox: -4, art: 'diary/apagador' },
  { id: 'd_globo', room: 'escola', x: 9, y: 0, ox: -4, art: 'diary/globo' },
  { id: 'd_dicionario', room: 'escola', x: 8, y: 0, ox: -4, art: 'diary/dicionario' },
  { id: 'd_grampeador', room: 'escola', x: 7, y: 4, ox: -4, art: 'diary/grampeador' },
  { id: 'd_clipe', room: 'escola', x: 7, y: 4, ox: 4, art: 'diary/clipe' },
  { id: 'd_pasta', room: 'escola', x: 6, y: 5, ox: -4, art: 'diary/pasta' },
  { id: 'd_cracha', room: 'escola', x: 7, y: 3, ox: -4, art: 'diary/cracha' },
  { id: 'd_sino', room: 'escola', x: 9, y: 5, ox: -4, art: 'diary/sino' },
  { id: 'd_corredor', room: 'escola', x: 9, y: 6, ox: -4, art: 'diary/corredor' },
  { id: 'd_patio', room: 'escola', x: 9, y: 4, ox: -4, art: 'diary/patio' },
  { id: 's_silencio', room: 'escola', x: 0, y: 5, w: 3, art: 'diary/sign_silencio', sign: { pt: "SILÊNCIO", en: "Silence" } },
  { id: 's_biblioteca', room: 'escola', x: 6, y: 6, w: 3, art: 'diary/sign_biblioteca', sign: { pt: "BIBLIOTECA", en: "Library" } },
  { id: 's_chamada', room: 'escola', x: 2, y: 0, w: 2, art: 'diary/sign_chamada', sign: { pt: "CHAMADA", en: "Roll call" } },
];
