// HUD icons, 16x16 pixel art (`ui/icon_<name>`): the top bar, the send button, the mission steps and the credits button. They replace the old
// SVG icons of the isometric era so the whole chrome is one pixel language. Authored as char grids in the pack's palette (navy outline, warm
// browns, terracotta / mustard / leaf green from the brand palette); light comes from the upper left.
import { blank, grid } from './paint.mjs';

const PAL = {
  o: '#3a3a50', // outline navy
  w: '#f5e6d3', // cream
  W: '#fffaf0', // highlight
  y: '#d4a017', // mustard
  Y: '#f0c94a', // mustard light
  t: '#c45c26', // terracotta
  T: '#a13a30', // terracotta dark
  g: '#2f5d50', // green dark
  G: '#4f9a6a', // green
  L: '#9bd38a', // green light
  b: '#4280dd', // blue
  B: '#95e3e3', // blue light
  n: '#8b5e3c', // wood
  N: '#573c2c', // wood dark
  s: '#f2c9a0', // skin
  S: '#d9a072', // skin shade
  p: '#e07070', // pink
  r: '#9a9a92', // grey
  R: '#cfc8bc', // grey light
};

const ICON_ROWS = {
  map: [
    '................',
    '................',
    '.oooooooooooooo.',
    '.oGGGoWWWWoBBBo.',
    '.oGLGoWWtWoBBbo.',
    '.oGGGoWWTtoBbbo.',
    '.oLGGoWtWWoBBbo.',
    '.oGGLoWtWWoBBBo.',
    '.oGGGoWWtWoBbBo.',
    '.oLGGoWWWWoBBBo.',
    '.oGGGoWWWWoBBBo.',
    '.oooooooooooooo.',
    '................',
    '................',
    '................',
    '................',
  ],
  hat: [
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '....oYYYYyyo....',
    '...oYYYyYyyyo...',
    '...oYYyYyYyyo...',
    '...oYyYyYyyyo...',
    '...ottttttttoo..',
    '...oTTTTTTTTo...',
    '.oooyYYyyyyyooo.',
    'oYYYYyyyyyyyyyyo',
    'oyyyyyyyyyyyyyyo',
    '.ooyyyyyyyyyyoo.',
    '...oooooooooo...',
    '................',
  ],
  friends: [
    '................',
    '................',
    '..oooo..........',
    '.oLGGGo..oooo...',
    '.oGsssGoosssBo..',
    '.oGssssosssssbo.',
    '.oGssssossssbbo.',
    '..oGGGoosbbbbo..',
    '.oGGGGGGobbbbbo.',
    'oGGGGGGGGobbbbbo',
    'oGGGGGGGGobbbbbo',
    'oGGGGGGGGobbbbbo',
    'oooooooooooooooo',
    '................',
    '................',
    '................',
  ],
  soundOn: [
    '................',
    '................',
    '.......oo.......',
    '......oYyo...W..',
    '.....oYYyo....W.',
    '.oooooYYyo.W...W',
    '.oYYyoYYyo..W..W',
    '.oYYyoYYyo..W..W',
    '.oYYyoYYyo..W..W',
    '.oYYyoYYyo.W...W',
    '.oooooYYyo....W.',
    '.....oYYyo...W..',
    '......oYyo......',
    '.......oo.......',
    '................',
    '................',
  ],
  soundOff: [
    '................',
    '................',
    '.......oo.......',
    '......oRro......',
    '.....oRRro.W..W.',
    '.oooooRRro..WW..',
    '.oRRroRRro..WW..',
    '.oRRroRRro..WW..',
    '.oRRroRRro..WW..',
    '.oRRroRRro..WW..',
    '.oooooRRro.W..W.',
    '.....oRRro......',
    '......oRro......',
    '.......oo.......',
    '................',
    '................',
  ],
  musicOn: [
    '................',
    '................',
    '.....oooooooooo.',
    '.....oYYYYYYYyo.',
    '.....oyyyyyyyyo.',
    '.....oooooooooo.',
    '.....oY.....oY..',
    '.....oy.....oy..',
    '.....oY.....oY..',
    '..ooooy..ooooy..',
    '.oYYYyo.oYYYyo..',
    '.oYYyyo.oYYyyo..',
    '..oyyo...oyyo...',
    '...oo.....oo....',
    '................',
    '................',
  ],
  musicOff: [
    '................',
    '................',
    '.....oooooooooo.',
    '.....oRRRRRRRro.',
    '.....orrrrrrrro.',
    '.....oooooooooo.',
    '.....oR.....oR..',
    '.....or.....or..',
    '.....oR.....oR..',
    '..oooor..oooor..',
    '.oRRRro.oRRRro..',
    '.oRRrro.oRRrro..',
    '..orro...orro...',
    '...oo.....oo....',
    '................',
    '................',
  ],
  decor: [
    '................',
    '................',
    '................',
    '..ooooooooooo...',
    '.oGGGGGGGGGGGo..',
    '.oGLLLLLLLLLGo..',
    'ooGLLLLLLLLLGoo.',
    'oGoGGGGGGGGGoGo.',
    'oGGoGGGGGGGGoGGo',
    'oGGGGGGGGGGGGGGo',
    'oggggggggggggggo',
    '.oooooooooooooo.',
    '..oN........No..',
    '..oo........oo..',
    '................',
    '................',
  ],
  parrot: [
    '................',
    '................',
    '.....oooo.......',
    '....oGGGGo......',
    '...oGLLGGGo.....',
    '...oGLoGGtto....',
    '...oGGGGGtTo....',
    '...oGGGGGooo....',
    '..oGGbGGGGo.....',
    '..oGGbbGGGo.....',
    '..oGGbbGGo......',
    '..ooGGGGoo......',
    '...oyoooyo......',
    '.nnnnnnnnnnnnnn.',
    '.NNNNNNNNNNNNNN.',
    '................',
  ],
  send: [
    '................',
    '................',
    '..o.............',
    '..owo...........',
    '..owwoo.........',
    '..owwwwoo.......',
    '..owwwwwwoo.....',
    '..owwwwwwwwoo...',
    '..oWwwwwwwwwwoo.',
    '..owwwwwoooooo..',
    '..owwwooTTo.....',
    '..ooooTTTo......',
    '....oTTTo.......',
    '.....ooo........',
    '................',
    '................',
  ],
  close: [
    '................',
    '................',
    '..oo........oo..',
    '.oWwo......owwo.',
    '..oWwo....owwo..',
    '...oWwo..owwo...',
    '....oWwoowwo....',
    '.....oWwwwo.....',
    '.....owwwwo.....',
    '....owwooWwo....',
    '...owwo..oWwo...',
    '..owwo....oWwo..',
    '.owwo......oWwo.',
    '..oo........oo..',
    '................',
    '................',
  ],
  info: [
    '................',
    '................',
    '.....oooooo.....',
    '...ooBBbbbboo...',
    '..oBBbbbbbbbbo..',
    '..oBbbbwwbbbbo..',
    '.oBbbbbwwbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.obbbbbwwbbbbbo.',
    '.obbbbbwwbbbbbo.',
    '..obbbbwwbbbbo..',
    '..obbbbwwbbbbo..',
    '...oobbbbbboo...',
    '.....oooooo.....',
    '................',
    '................',
  ],
  logout: [
    '................',
    '................',
    '.oooooooo.......',
    '.oTtttttto......',
    '.oTtttttto......',
    '.oTtttttto...W..',
    '.oTtttttto...WW.',
    '.oTtttyttoWWWWWW',
    '.oTtttyttoWWWWWW',
    '.oTtttttto...WW.',
    '.oTtttttto...W..',
    '.oTtttttto......',
    '.oooooooooo.....',
    '................',
    '................',
    '................',
  ],
  cumprimenta: [
    '................',
    '................',
    '...oo.oo.oo.oo..',
    '..ossossossosso.',
    '..ossossossosso.',
    '..ossossossosso.',
    '..osssssssssso..',
    '..osssssssssso..',
    '..osssssssssso..',
    '..ossssssssSso..',
    '...ossssssssSo..',
    '...osssssssSSo..',
    '....oTttttttTo..',
    '....oooooooooo..',
    '................',
    '................',
  ],
  pede: [
    '................',
    '....o..o..o.....',
    '...oT.oT.oT.....',
    '....o.oT..o.....',
    '................',
    '.oooooooooo.....',
    '.oWwwwwwwwoooo..',
    '.oNNNNNNNNoWwwo.',
    '.oNnnnnnnNo..oo.',
    '.owwwwwwwwo..ow.',
    '.owwwwwwwwo.oww.',
    '..owwwwwwo.ow...',
    '...oooooo.oo....',
    '.oooooooooooo...',
    '................',
    '................',
  ],
  monta: [
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '....oYYYYYyo....',
    '...oYYwYYyyyo...',
    '..oYYYYYYyyyyo..',
    '..oyyyyyyyyyyo..',
    '...ooooooooooo..',
    '.oooooooooooooo.',
    'oTttttttttttttTo',
    '.oTTTTTTTTTTTTo.',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
  ],
};

export const UI_ICON_NAMES = Object.keys(ICON_ROWS);

function draw(rows) {
  if (rows.length !== 16) throw new Error(`ui icon needs 16 rows, got ${rows.length}`);
  rows.forEach((r, i) => {
    if (r.length !== 16) throw new Error(`ui icon row ${i} has ${r.length} chars: "${r}"`);
  });
  const img = blank(16, 16);
  grid(img, rows, PAL, 0, 0);
  return img;
}

export async function uiIconParts() {
  return UI_ICON_NAMES.map((name) => ({ key: `ui/icon_${name}`, img: draw(ICON_ROWS[name]) }));
}
export async function preview() {
  return UI_ICON_NAMES.map((name) => draw(ICON_ROWS[name]));
}
