import { chromium } from 'playwright-core';
const BASE = 'http://localhost:8801';
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch({ executablePath: CHROME, headless: true });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
page.on('console', (m) => console.log('console', m.text().slice(0, 200)));
page.on('pageerror', (e) => console.error('pageerror', String(e)));
await page.goto(BASE);
await page.waitForSelector('#intro-enter');
await page.click('#intro-enter');
await page.waitForSelector('#intro-skip');
await page.click('#intro-skip');
await page.waitForSelector('#intro-guest', { state: 'visible' });
await page.click('#intro-tab-register');
await page.fill('#intro-email', `dbg${Date.now().toString(36)}@exemplo.com`);
await page.fill('#intro-password', 'pao-de-queijo-2026');
await page.click('#intro-submit');
await page.waitForSelector('#avatar-name');
await page.fill('#avatar-name', 'Jonny');
await page.click('button:has-text("ele (he)")');
await page.click('#enter-praca');
await page.waitForFunction(() => window.__tb.game.room?.room === 'praca');
await sleep(3000);
console.log(await page.evaluate(() => JSON.stringify(window.__tb.selfTile())));
for (const [x,y] of [[25,25],[25,19],[27,19],[26,13],[30,13],[8,27]]) {
  await page.evaluate(([x,y]) => window.__tb.walkTo(x,y), [x,y]);
  await sleep(2500);
  console.log(x,y, await page.evaluate(() => JSON.stringify(window.__tb.selfTile())));
}
await browser.close();
